// GENERATED by tool/generate_palette.py from the TickTick color reference (tokens_temas.json). Do not edit by hand.

import 'dart:ui';

/// One theme's palette: the webapp's `--color-*` variables.
///
/// TickTick's "grey" texts and fills are `grey` with an opacity level (see `level` in level.dart).
class TtPalette {
  const TtPalette({
    required this.black,
    required this.brandBlack,
    required this.brandPrimary,
    required this.brandSecondary,
    required this.btnActiveColor,
    required this.btnDisableColor,
    required this.btnHoverColor,
    required this.cancelBtnActive,
    required this.cancelBtnHover,
    required this.cardBg,
    required this.cardModeColor,
    required this.darkCardBg,
    required this.darkRed,
    required this.gallery,
    required this.green,
    required this.grey,
    required this.highlight,
    required this.highlightSub,
    required this.leftSidebarBgColor,
    required this.leftSidebarColor,
    required this.lightBlack,
    required this.mainBackground,
    required this.menuPrimary,
    required this.minCalColor,
    required this.orange,
    required this.primary,
    required this.primaryFront,
    required this.priorityHigh,
    required this.priorityLow,
    required this.priorityMedium,
    required this.pro,
    required this.screenBackground,
    required this.sidebarBgColor,
    required this.sidebarColor,
    required this.sidebarIconNumberColor,
    required this.summerBg,
    required this.teamOrange,
    required this.teamOrangeActive,
    required this.teamOrangeDisable,
    required this.teamOrangeHover,
    required this.turquoise,
    required this.warnRed,
    required this.white,
    required this.leftViewBackgroundOpacity,
  });

  final Color black;
  final Color brandBlack;
  final Color brandPrimary;
  final Color brandSecondary;
  final Color btnActiveColor;
  final Color btnDisableColor;
  final Color btnHoverColor;
  final Color cancelBtnActive;
  final Color cancelBtnHover;
  final Color cardBg;
  final Color cardModeColor;
  final Color darkCardBg;
  final Color darkRed;
  final Color gallery;
  final Color green;
  final Color grey;
  final Color highlight;
  final Color highlightSub;
  final Color leftSidebarBgColor;
  final Color leftSidebarColor;
  final Color lightBlack;
  final Color mainBackground;
  final Color menuPrimary;
  final Color minCalColor;
  final Color orange;
  final Color primary;
  final Color primaryFront;
  final Color priorityHigh;
  final Color priorityLow;
  final Color priorityMedium;
  final Color pro;
  final Color screenBackground;
  final Color sidebarBgColor;
  final Color sidebarColor;
  final Color sidebarIconNumberColor;
  final Color summerBg;
  final Color teamOrange;
  final Color teamOrangeActive;
  final Color teamOrangeDisable;
  final Color teamOrangeHover;
  final Color turquoise;
  final Color warnRed;
  final Color white;

  /// `--opacity-variant-main-background-left-view` (the only opacity that is not level/100).
  final double leftViewBackgroundOpacity;

  /// The same palette with another primary color (Settings → Aparência → Série de Cores).
  TtPalette withPrimary(Color primary) => TtPalette(
    black: black,
    brandBlack: brandBlack,
    brandPrimary: brandPrimary,
    brandSecondary: brandSecondary,
    btnActiveColor: btnActiveColor,
    btnDisableColor: btnDisableColor,
    btnHoverColor: btnHoverColor,
    cancelBtnActive: cancelBtnActive,
    cancelBtnHover: cancelBtnHover,
    cardBg: cardBg,
    cardModeColor: cardModeColor,
    darkCardBg: darkCardBg,
    darkRed: darkRed,
    gallery: gallery,
    green: green,
    grey: grey,
    highlight: highlight,
    highlightSub: highlightSub,
    leftSidebarBgColor: leftSidebarBgColor,
    leftSidebarColor: leftSidebarColor,
    lightBlack: lightBlack,
    mainBackground: mainBackground,
    menuPrimary: menuPrimary,
    minCalColor: minCalColor,
    orange: orange,
    primary: primary,
    primaryFront: primaryFront,
    priorityHigh: priorityHigh,
    priorityLow: priorityLow,
    priorityMedium: priorityMedium,
    pro: pro,
    screenBackground: screenBackground,
    sidebarBgColor: sidebarBgColor,
    sidebarColor: sidebarColor,
    sidebarIconNumberColor: sidebarIconNumberColor,
    summerBg: summerBg,
    teamOrange: teamOrange,
    teamOrangeActive: teamOrangeActive,
    teamOrangeDisable: teamOrangeDisable,
    teamOrangeHover: teamOrangeHover,
    turquoise: turquoise,
    warnRed: warnRed,
    white: white,
    leftViewBackgroundOpacity: leftViewBackgroundOpacity,
  );
}

/// TickTick theme `white-theme`.
const lightPalette = TtPalette(
  black: Color(0xFF000000),
  brandBlack: Color(0xFF191919),
  brandPrimary: Color(0xFF4772FA),
  brandSecondary: Color(0xFFFFB000),
  btnActiveColor: Color(0xFF3E60CD),
  btnDisableColor: Color(0xFFB5C7FD),
  btnHoverColor: Color(0xFF6C8EFB),
  cancelBtnActive: Color(0xFFE8E8E8),
  cancelBtnHover: Color(0xFFF4F4F4),
  cardBg: Color(0xFFFAFAFA),
  cardModeColor: Color(0xFFFFFFFF),
  darkCardBg: Color(0xFF1E1E1E),
  darkRed: Color(0xFFE03131),
  gallery: Color(0xFFEEEEEE),
  green: Color(0xFF0CCE9C),
  grey: Color(0xFF191919),
  highlight: Color(0xFFFBC140),
  highlightSub: Color(0xFFF2D9A2),
  leftSidebarBgColor: Color(0xFFF5F5F5),
  leftSidebarColor: Color(0xFFFFFFFF),
  lightBlack: Color(0xFF333333),
  mainBackground: Color(0xFFFFFFFF),
  menuPrimary: Color(0xFF4772FA),
  minCalColor: Color(0xFFFFFFFF),
  orange: Color(0xFFFF5900),
  primary: Color(0xFF4772FA),
  primaryFront: Color(0xFF000000),
  priorityHigh: Color(0xFFE13E39),
  priorityLow: Color(0xFF4772FA),
  priorityMedium: Color(0xFFFAA80C),
  pro: Color(0xFFFF8E0A),
  screenBackground: Color(0xFFFFFFFF),
  sidebarBgColor: Color(0xFFF2F5FE),
  sidebarColor: Color(0xFF191919),
  sidebarIconNumberColor: Color(0xFFF2F5FE),
  summerBg: Color(0xFF055D74),
  teamOrange: Color(0xFFFB8142),
  teamOrangeActive: Color(0xFFCE6C3A),
  teamOrangeDisable: Color(0xFFFDCDB3),
  teamOrangeHover: Color(0xFFFC9A68),
  turquoise: Color(0xFF10C3EE),
  warnRed: Color(0xFFE03131),
  white: Color(0xFFFFFFFF),
  leftViewBackgroundOpacity: 0.6,
);

/// TickTick theme `night-dark-theme`.
const darkPalette = TtPalette(
  black: Color(0xFF000000),
  brandBlack: Color(0xFF191919),
  brandPrimary: Color(0xFF4772FA),
  brandSecondary: Color(0xFFFFB000),
  btnActiveColor: Color(0xFF3E60CD),
  btnDisableColor: Color(0xFF33447B),
  btnHoverColor: Color(0xFF4063D0),
  cancelBtnActive: Color(0xFF3C3C3C),
  cancelBtnHover: Color(0xFF313131),
  cardBg: Color(0xFFFAFAFA),
  cardModeColor: Color(0xFF222222),
  darkCardBg: Color(0xFF1E1E1E),
  darkRed: Color(0xFFE03131),
  gallery: Color(0xFFEEEEEE),
  green: Color(0xFF0CCE9C),
  grey: Color(0xFFFFFFFF),
  highlight: Color(0xFFC68B16),
  highlightSub: Color(0xFF7D612E),
  leftSidebarBgColor: Color(0xFF242424),
  leftSidebarColor: Color(0xFFFFFFFF),
  lightBlack: Color(0xFF333333),
  mainBackground: Color(0xFF242424),
  menuPrimary: Color(0xFF4772FA),
  minCalColor: Color(0xFFFFFFFF),
  orange: Color(0xFFFF5900),
  primary: Color(0xFF4772FA),
  primaryFront: Color(0xFFFFFFFF),
  priorityHigh: Color(0xFFE13E39),
  priorityLow: Color(0xFF4772FA),
  priorityMedium: Color(0xFFFAA80C),
  pro: Color(0xFFFF8E0A),
  screenBackground: Color(0xFF1C1C1C),
  sidebarBgColor: Color(0xFF1C1C1C),
  sidebarColor: Color(0xFFFFFFFF),
  sidebarIconNumberColor: Color(0xFF191919),
  summerBg: Color(0xFF055D74),
  teamOrange: Color(0xFFFB8142),
  teamOrangeActive: Color(0xFFCE6C3A),
  teamOrangeDisable: Color(0xFFFDCDB3),
  teamOrangeHover: Color(0xFFFC9A68),
  turquoise: Color(0xFF10C3EE),
  warnRed: Color(0xFFE03131),
  white: Color(0xFFFFFFFF),
  leftViewBackgroundOpacity: 0.8,
);
