"""Generates lib/app/theme/palette_generated.dart from the TickTick color reference, tokens_temas.json,
kept with the working notes outside the repository (_notas/referencia/, on the developer's PC).

Usage (inside app/):  python tool/generate_palette.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / '_notas' / 'referencia' / 'tokens_temas.json'
TARGET = ROOT / 'lib' / 'app' / 'theme' / 'palette_generated.dart'

# TickTick theme name -> Dart constant name.
THEMES = {'white-theme': 'lightPalette', 'night-dark-theme': 'darkPalette'}


def camel(name: str) -> str:
    parts = re.split(r'[-_]', name)
    return parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])


def color(rgb: str) -> str:
    r, g, b = (int(x) for x in rgb.split(','))
    return f'Color(0xFF{r:02X}{g:02X}{b:02X})'


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding='utf-8'))
    themes = data['temas']
    names = sorted(next(iter(themes.values()))['cores'])
    for theme in themes.values():
        if sorted(theme['cores']) != names:
            raise SystemExit('Every theme must define the same colors.')

    lines = [
        '// GENERATED by tool/generate_palette.py from the TickTick color reference (tokens_temas.json). Do not edit by hand.',
        '',
        "import 'dart:ui';",
        '',
        "/// One theme's palette: the webapp's `--color-*` variables.",
        '///',
        '/// TickTick\'s "grey" texts and fills are `grey` with an opacity level (see `level` in level.dart).',
        'class TtPalette {',
        '  const TtPalette({',
    ]
    lines += [f'    required this.{camel(n)},' for n in names]
    lines += ['    required this.leftViewBackgroundOpacity,', '  });', '']
    lines += [f'  final Color {camel(n)};' for n in names]
    lines += [
        '',
        '  /// `--opacity-variant-main-background-left-view` (the only opacity that is not level/100).',
        '  final double leftViewBackgroundOpacity;',
        '',
        '  /// The same palette with another primary color (Settings → Aparência → Série de Cores).',
        '  TtPalette withPrimary(Color primary) => TtPalette(',
    ]
    lines += [f'    {camel(n)}: {"primary" if camel(n) == "primary" else camel(n)},' for n in names]
    lines += [
        '    leftViewBackgroundOpacity: leftViewBackgroundOpacity,',
        '  );',
        '}',
        '',
    ]
    for key, const in THEMES.items():
        theme = themes[key]
        left = float(theme['opacidades_especiais']['--opacity-variant-main-background-left-view'])
        lines.append(f'/// TickTick theme `{key}`.')
        lines.append(f'const {const} = TtPalette(')
        lines += [f'  {camel(n)}: {color(theme["cores"][n])},' for n in names]
        lines.append(f'  leftViewBackgroundOpacity: {left},')
        lines.append(');')
        lines.append('')

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
    print(f'{TARGET.relative_to(ROOT)}: {len(names)} colors x {len(THEMES)} themes')


if __name__ == '__main__':
    main()
