"""Draws the app icon (provisional) and writes every size Android and Windows need.

Run from the app folder:  python tool/make_icons.py   (needs Pillow: pip install pillow)
To change the icon, edit COLOR or draw_mark() and run it again.
"""
from pathlib import Path

from PIL import Image, ImageDraw

COLOR = (0x47, 0x72, 0xFA)  # the app's primary blue
WHITE = (255, 255, 255)
ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / 'android' / 'app' / 'src' / 'main' / 'res'
SUPER = 4  # drawn larger, then scaled down, for smooth edges


def draw_mark(draw: ImageDraw.ImageDraw, box: tuple[float, float, float, float], color) -> None:
    """A checked box followed by two list lines, inside [box] (left, top, right, bottom)."""
    left, top, right, bottom = box
    size = right - left
    stroke = size * 0.085
    # Checkbox.
    cb = size * 0.42
    cx0, cy0 = left + size * 0.02, top + (size - cb) / 2
    draw.rounded_rectangle((cx0, cy0, cx0 + cb, cy0 + cb), radius=cb * 0.22, outline=color, width=round(stroke))
    # Check mark inside it.
    points = [(cx0 + cb * 0.24, cy0 + cb * 0.52), (cx0 + cb * 0.43, cy0 + cb * 0.71), (cx0 + cb * 0.78, cy0 + cb * 0.30)]
    draw.line(points, fill=color, width=round(stroke), joint='curve')
    for x, y in (points[0], points[-1]):
        r = stroke / 2
        draw.ellipse((x - r, y - r, x + r, y + r), fill=color)
    # Two lines on the right, the second shorter.
    lx = cx0 + cb + size * 0.1
    for i, length in enumerate((0.44, 0.30)):
        y = top + size * (0.42 + 0.17 * i)
        draw.rounded_rectangle((lx, y - stroke / 2, lx + size * length, y + stroke / 2), radius=stroke / 2, fill=color)


def full_icon(px: int) -> Image.Image:
    """Blue rounded square with the white mark (legacy Android icon, Windows)."""
    s = px * SUPER
    img = Image.new('RGBA', (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.rounded_rectangle((0, 0, s - 1, s - 1), radius=s * 0.22, fill=COLOR + (255,))
    pad = s * 0.13
    draw_mark(d, (pad, pad, s - pad, s - pad), WHITE)
    return img.resize((px, px), Image.LANCZOS)


def foreground(px: int, color) -> Image.Image:
    """Adaptive icon layer: the mark alone. Launchers show only the middle 72/108 and mask it (circle,
    squircle), so the mark keeps to 48/108."""
    s = px * SUPER
    img = Image.new('RGBA', (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    pad = s * (1 - 48 / 108) / 2
    draw_mark(d, (pad, pad, s - pad, s - pad), color)
    return img.resize((px, px), Image.LANCZOS)


def main() -> None:
    densities = {'mdpi': 1, 'hdpi': 1.5, 'xhdpi': 2, 'xxhdpi': 3, 'xxxhdpi': 4}
    for name, scale in densities.items():
        folder = RES / f'mipmap-{name}'
        folder.mkdir(parents=True, exist_ok=True)
        full_icon(round(48 * scale)).save(folder / 'ic_launcher.png')
        foreground(round(108 * scale), WHITE).save(folder / 'ic_launcher_foreground.png')
        foreground(round(108 * scale), WHITE).save(folder / 'ic_launcher_monochrome.png')

    anydpi = RES / 'mipmap-anydpi-v26'
    anydpi.mkdir(exist_ok=True)
    (anydpi / 'ic_launcher.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/make_icons.py -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />\n'
        '</adaptive-icon>\n',
        encoding='utf-8',
        newline='\n',
    )
    (RES / 'values' / 'ic_launcher_background.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/make_icons.py -->\n'
        '<resources>\n'
        '    <color name="ic_launcher_background">#%02X%02X%02X</color>\n'
        '</resources>\n' % COLOR,
        encoding='utf-8',
        newline='\n',
    )

    ico = ROOT / 'windows' / 'runner' / 'resources' / 'app_icon.ico'
    full_icon(256).save(ico, sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    full_icon(512).save(ROOT / 'tool' / 'icon_preview.png')
    print('icons written')


if __name__ == '__main__':
    main()
